name: Linter

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint:
    strategy:
      matrix:
        os: [ ubuntu-latest ]
        node: [ 15 ]
    runs-on: ${{ matrix.os }}
  
    steps:
      - name: Checkout master branch
        uses: actions/checkout@v2
        
      - name: Setup Node.js environment
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
          cache: npm
          cache-dependency-path: 'package-lock.json'

      - name: Install dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: npm install

      - name: Run ESLint
        run: npm run lint

      - name: Check build
        run: npm run build
